# Generated by Django 5.1.3 on 2024-12-08 22:23

import appManageWSSP.datavalidation
import appManageWSSP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appManageWSSP', '0002_element_mediaresource_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='file_image',
            field=models.FileField(storage='appManageWSSP.storage_backend.SupabaseStorage', unique=True, upload_to=appManageWSSP.models.custom_media_path, validators=[appManageWSSP.datavalidation.valid_image_extension, appManageWSSP.datavalidation.valid_image_file_size, appManageWSSP.datavalidation.valid_file_name]),
        ),
    ]
