# Generated by Django 5.1.3 on 2024-12-08 22:29

import appManageWSSP.datavalidation
import appManageWSSP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appManageWSSP', '0003_alter_imagen_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='file_image',
            field=models.FileField(unique=True, upload_to=appManageWSSP.models.custom_media_path, validators=[appManageWSSP.datavalidation.valid_image_extension, appManageWSSP.datavalidation.valid_image_file_size, appManageWSSP.datavalidation.valid_file_name]),
        ),
    ]
